[package]
name = "qumulus"
version = "0.1.0"
authors = ["Kwok Yang Bin <yangbin@fragnetics.com>"]

[dependencies]
mioco = { git = "https://github.com/dpc/mioco.git" }
serde = "*"
serde_json = "*"
time = "*"
